name       : cvc4          # name of the package
version    : 1.4.0-2       # version of the package
kind       : tool                     # one of tool or spec(s)
description: CVC4 is an efficient open-source automatic theorem prover for satisfiability modulo theories (SMT) problems. 

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com



assets:
    - asset   : MAIN
      name    : CVC4 Solver Binary for Windows
      url     : http://cvc4.cs.nyu.edu/builds/win32-opt/cvc4-1.4-win32-opt.exe
      platform: windows
    - asset   : MAIN
      name    : CVC4 Solver Binary for Linux
      url     : http://cvc4.cs.nyu.edu/builds/x86_64-linux-opt/cvc4-1.4-x86_64-linux-opt
      platform: linux
    - asset   : MAIN
      name    : CVC4 Solver Distribution for OSX
      url     : https://github.com/Spekl/static-files/releases/download/cvc4-1.4.0/cvc4-1.4.0-mac.tar.gz
      platform: osx
        
install:
  - cmd: cp MAIN cvc4
    description: Normalizing cvc4 Binary...
    platform: windows
  - cmd: cp MAIN cvc4
    description: Normalizing cvc4 Binary...
    platform: linux
  - cmd: tar -zxvf MAIN
    description: Extracting CVC4 Distribution...
    platform: osx
  - cmd: ln -s cvc4-1.4.0/bin/cvc4 cvc4.bin
    description: Linking binary...
    platform: osx
  - cmd: mv cvc4.osx.sh cvc4
    description: Adding OSX Shims...
    platform: osx
  - cmd: chmod +x cvc4
    description: Setting Shim Executable...
    platform: osx
